export const categoryOptions = [
    { value: 'arts', label: 'Arts' },
    { value: 'automotive', label: 'Automotive' },
    { value: 'astrology', label: 'Astrology' },
    { value: 'business', label: 'Business' },
    { value: 'budget_travel', label: 'Budget Travel' },
    { value: 'books', label: 'Books' },
    { value: 'blogging', label: 'Blogging' },
    { value: 'brand', label: 'Brand' },
    { value: 'cooking', label: 'Cooking' },
    { value: 'craft', label: 'Craft' },
    { value: 'crafts', label: 'Crafts' },
    { value: 'customer_service', label: 'Customer Service' },
    { value: 'decor', label: 'Decor' },
    { value: 'design', label: 'Design' },
    { value: 'digital_marketing', label: 'Digital Marketing' },
    { value: 'diary', label: 'Diary' },
    { value: 'education', label: 'Education' },
    { value: 'entertainment', label: 'Entertainment' },
    { value: 'entrepreneurship', label: 'Entrepreneurship' },
    { value: 'events', label: 'Events' },
    { value: 'events_planning', label: 'Events Planning' },
    { value: 'ecommerce', label: 'E-commerce' },
    { value: 'fashion', label: 'Fashion' },
    { value: 'fitness', label: 'Fitness' },
    { value: 'fitness_tips', label: 'Fitness Tips' },
    { value: 'food', label: 'Food' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'gaming_news', label: 'Gaming News' },
    { value: 'geography', label: 'Geography' },
    { value: 'government', label: 'Government' },
    { value: 'green_living', label: 'Green Living' },
    { value: 'health', label: 'Health' },
    { value: 'history', label: 'History' },
    { value: 'home_decor', label: 'Home Decor' },
    { value: 'home_improvement', label: 'Home Improvement' },
    { value: 'humor', label: 'Humor' },
    { value: 'interior_design', label: 'Interior Design' },
    { value: 'interviews', label: 'Interviews' },
    { value: 'investing', label: 'Investing' },
    { value: 'law', label: 'Law' },
    { value: 'language', label: 'Language' },
    { value: 'lifestyle', label: 'Lifestyle' },
    { value: 'marketing', label: 'Marketing' },
    { value: 'mental_health', label: 'Mental Health' },
    { value: 'movies', label: 'Movies' },
    { value: 'music', label: 'Music' },
    { value: 'news', label: 'News' },
    { value: 'nonprofit', label: 'Nonprofit' },
    { value: 'nutrition', label: 'Nutrition' },
    { value: 'outdoors', label: 'Outdoors' },
    { value: 'parenting', label: 'Parenting' },
    { value: 'parenting_tips', label: 'Parenting Tips' },
    { value: 'pets', label: 'Pets' },
    { value: 'philosophy', label: 'Philosophy' },
    { value: 'photographers', label: 'Photographers' },
    { value: 'photography', label: 'Photography' },
    { value: 'photography_tips', label: 'Photography Tips' },
    { value: 'productivity', label: 'Productivity' },
    { value: 'public_speaking', label: 'Public Speaking' },
    { value: 'real_estate', label: 'Real Estate' },
    { value: 'real_estate_investment', label: 'Real Estate Investment' },
    { value: 'relationships', label: 'Relationships' },
    { value: 'research', label: 'Research' },
    { value: 'reviews', label: 'Reviews' },
    { value: 'sociology', label: 'Sociology' },
    { value: 'self_improvement', label: 'Self Improvement' },
    { value: 'shopping', label: 'Shopping' },
    { value: 'social_issues', label: 'Social Issues' },
    { value: 'social_media', label: 'Social Media' },
    { value: 'sports', label: 'Sports' },
    { value: 'sports_news', label: 'Sports News' },
    { value: 'startup', label: 'Startup' },
    { value: 'stock_market', label: 'Stock Market' },
    { value: 'sustainable_living', label: 'Sustainable Living' },
    { value: 'technology', label: 'Technology' },
    { value: 'technology_news', label: 'Technology News' },
    { value: 'technology_reviews', label: 'Technology Reviews' },
    { value: 'team_building', label: 'Team Building' },
    { value: 'travel', label: 'Travel' },
    { value: 'travel_guides', label: 'Travel Guides' },
    { value: 'travel_tips', label: 'Travel Tips' },
    { value: 'vacations', label: 'Vacations' },
    { value: 'video', label: 'Video' },
    { value: 'volunteering', label: 'Volunteering' },
    { value: 'web_design', label: 'Web Design' },
    { value: 'woodworking', label: 'Woodworking' },
    { value: 'yoga', label: 'Yoga' },
    { value: 'other', label: 'Other' },
  ];